from typing import Protocol


class CacheProtocol(Protocol):
    async def get(self, key): ...

    async def set(self, key, value, ttl: int | None = None): ...

    async def delete(self, key): ...

    def __getitem__(self, key): ...

    def __setitem__(self, key, value, ttl: int | None = None): ...

    def __delitem__(self, key): ...


class AuthProtocol(Protocol):
    async def get_user_info(self, token): ...

    async def get_user_id_by_token(self, token): ...

    async def get_token_expiration_time(self, token): ...
